# Generated by Django 3.1.5 on 2021-03-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_registrant',
            field=models.CharField(default='asdas', max_length=50, verbose_name='房间操作人'),
            preserve_default=False,
        ),
    ]
