# Generated by Django 3.1.5 on 2021-03-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_room_room_registrant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_registrant',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='房间操作人'),
        ),
    ]
