# Generated by Django 3.1.5 on 2021-03-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20210319_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='电话号码'),
        ),
    ]
