# Generated by Django 3.1.5 on 2021-03-23 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0004_auto_20210319_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_date', models.DateTimeField(verbose_name='入住时间')),
                ('cancel_date', models.DateTimeField(verbose_name='退房时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='记录所有人')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.room', verbose_name='房间号')),
            ],
            options={
                'verbose_name': '房间时间',
                'verbose_name_plural': '房间时间',
            },
        ),
    ]
