# Generated by Django 3.1.5 on 2021-03-23 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_room_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='book_date',
        ),
        migrations.RemoveField(
            model_name='room',
            name='cancel_date',
        ),
        migrations.RemoveField(
            model_name='room',
            name='option_book',
        ),
        migrations.RemoveField(
            model_name='room',
            name='option_live',
        ),
    ]
