# Generated by Django 3.1.5 on 2021-03-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20210323_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_record',
            name='book_date',
            field=models.DateField(verbose_name='入住时间'),
        ),
        migrations.AlterField(
            model_name='booking_record',
            name='cancel_date',
            field=models.DateField(verbose_name='退房时间'),
        ),
        migrations.AlterField(
            model_name='room_date',
            name='book_date',
            field=models.DateField(verbose_name='入住时间'),
        ),
        migrations.AlterField(
            model_name='room_date',
            name='cancel_date',
            field=models.DateField(verbose_name='退房时间'),
        ),
    ]
