# Generated by Django 3.1.5 on 2021-03-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20210324_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_date',
            name='date_id',
            field=models.IntegerField(auto_created=True, blank=True, default=1, verbose_name='日期号'),
            preserve_default=False,
        ),
    ]
