# Generated by Django 3.1.5 on 2021-03-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20210325_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_date',
            name='date_id',
            field=models.UUIDField(auto_created=True, verbose_name='日期号'),
        ),
    ]
