# Generated by Django 3.1.5 on 2021-03-25 15:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_auto_20210325_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_date',
            name='date_id',
            field=models.UUIDField(default=uuid.UUID('d3b8cf64-8d3f-11eb-b0ab-38d5478cd9b2'), verbose_name='日期号'),
        ),
    ]
