# Generated by Django 3.1.5 on 2021-03-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_auto_20210325_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_date',
            name='date_id',
            field=models.UUIDField(verbose_name='日期号'),
        ),
    ]
