# Generated by Django 3.1.5 on 2021-03-25 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_auto_20210325_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room_date',
            name='date_id',
        ),
    ]
