# Generated by Django 3.1.5 on 2021-03-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_remove_room_date_date_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_date',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='预订客户姓名'),
        ),
        migrations.AddField(
            model_name='room_date',
            name='tel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='预订电话号码'),
        ),
    ]
