# Generated by Django 3.1.5 on 2021-03-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_auto_20210325_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_date',
            name='max_day',
            field=models.IntegerField(blank=True, null=True, verbose_name='预订天数'),
        ),
    ]
