# Generated by Django 3.1.5 on 2021-03-25 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_room_date_max_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room_date',
            old_name='max_day',
            new_name='book_day',
        ),
    ]
