# Generated by Django 3.1.5 on 2021-03-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_auto_20210325_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='crash',
        ),
        migrations.RemoveField(
            model_name='room',
            name='deposit',
        ),
        migrations.AddField(
            model_name='room_date',
            name='crash',
            field=models.IntegerField(blank=True, null=True, verbose_name='实收房价'),
        ),
        migrations.AddField(
            model_name='room_date',
            name='deposit',
            field=models.IntegerField(blank=True, null=True, verbose_name='押金'),
        ),
    ]
