# Generated by Django 3.1.5 on 2021-03-27 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0019_auto_20210325_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crash', models.IntegerField(verbose_name='实收房价')),
                ('book_date', models.DateField(verbose_name='入住时间')),
                ('cancel_date', models.DateField(verbose_name='退房时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='记录所有人')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.room', verbose_name='房间号')),
            ],
            options={
                'verbose_name': '营收',
                'verbose_name_plural': '营收',
            },
        ),
    ]
