# Generated by Django 3.1.5 on 2021-03-29 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_registrant',
        ),
        migrations.AddField(
            model_name='booking_record',
            name='room_registrant',
            field=models.CharField(default=111, max_length=50, verbose_name='房间操作人'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room_date',
            name='book_date',
            field=models.DateField(default=datetime.date(1970, 1, 1), verbose_name='入住时间'),
        ),
        migrations.AlterField(
            model_name='room_date',
            name='cancel_date',
            field=models.DateField(default=datetime.date(1970, 1, 3), verbose_name='退房时间'),
        ),
    ]
