# Generated by Django 3.1.5 on 2021-03-19 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.CharField(max_length=50, verbose_name='员工身份证')),
                ('tel', models.CharField(blank=True, max_length=50, null=True, verbose_name='电话号码')),
                ('lord', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='员工所有人')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'unique_together': {('lord', 'id_card')},
            },
        ),
    ]
