# Generated by Django 3.1.5 on 2021-03-19 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='员工'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='staff',
            name='lord',
        ),
    ]
