# Generated by Django 3.1.5 on 2021-03-19 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_auto_20210319_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='员工所有人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='staffname',
            field=models.CharField(default=1, max_length=50, verbose_name='员工姓名'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together={('owner', 'id_card')},
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
    ]
