# Generated by Django 3.1.5 on 2021-03-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210319_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='first_name',
            field=models.CharField(default=11, max_length=50, verbose_name='店长权限'),
            preserve_default=False,
        ),
    ]
