# Generated by Django 3.1.5 on 2021-03-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_staff_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(default=111, max_length=50, verbose_name='员工密码'),
            preserve_default=False,
        ),
    ]
