# Generated by Django 3.1.5 on 2021-03-19 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210319_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='staffname',
            new_name='username',
        ),
    ]
