# Generated by Django 3.1.5 on 2021-03-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210319_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='tel',
            field=models.CharField(default=111, max_length=50, verbose_name='电话号码'),
            preserve_default=False,
        ),
    ]
